### ISSUE TITLE
Artifacts left behind after running top in tmux 

### ISSUE THREAD

**Issue by daviesalex** [liamg/aminal#127] opened 2019-01-08 00:25 UTC
**Describe the bug**
Artifacts left behind in some cases

**To Reproduce**
1. Open Aminal on Windows, SSH to a Linux box
2. Start a tmux session (tmux new-session, etc.)
3. Run "htop" or something similar
4. Detach tmux (ctrl+B, d)
5. You will see a load of artifacts left behind on the terminal

**Expected behavior**
Terminal should clear

**Screenshots**
![image](https://user-images.githubusercontent.com/1106249/50801255-cb551780-12db-11e9-9d98-fb466deadeec.png)

![image](https://user-images.githubusercontent.com/1106249/50801257-ce500800-12db-11e9-9615-066e3f6d5ad4.png)

**Environment (please complete the following information):**
 - OS + Version: Windows 10 1809
 - Go Version [e.g. 1.10.1] - 1.10
 - Shell [e.g. Bash/Zsh] - Bash

**Comment by daviesalex** [comment] 2019-01-10 23:13
This mostly seems effective, but I still got some examples where we are not clearing after running the latest build:

![image](https://user-images.githubusercontent.com/1106249/51003091-126d2380-14fb-11e9-96a1-ac7cf58c3a60.png)

**Comment by MaxRis** [comment] 2019-01-11 09:32
Probably, some more places exist with erasing of cell, but without resetting of background

**Comment by MaxRis** [comment] 2019-01-11 09:38
it looks like the artifact is just highlighted cells selected by mouse pointer. At least the color the same as Aminal do for selection by mouse pointer.
![selectioncolor](https://user-images.githubusercontent.com/1928902/51025699-6af0ff00-1595-11e9-848e-2dab39e1a1f3.png)

**Comment by daviesalex** [comment] 2019-01-11 18:59
While trying to reproduce this I made an interesting observation. If you select an area two things are curious:
- If you select an area, then click outside or in it, sometimes it takes a short period of time but sometimes several seconds to actually clear
- I was able to about one in ten times have a single click *not* clear the area (this may have been what I saw in this ticket that caused us to re-open it).

**Comment by nikitar020** [comment] 2019-01-25 13:57
I was not able to reproduce the problem according to the initial description - it seems that it has already been fixed by another commit.

But I found another bug related to this - the selection is not cleared when switching between `tmux` windows. Other terminal emulators (e.g. `putty`) do clear selected area in such cases.

**Closed** 2019-01-25 16:47 UTC
Labels: bug
