### ISSUE TITLE
Render error: Failed to create window: Failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by neyuki** [liamg/aminal#83] opened 2018-11-28 12:03 UTC
Just tried to run aminal-linux-amd64 from releases, and got:

`1.543406135031648e+09   info    aminal/main.go:28       Allocating pty...
1.5434061350458617e+09  info    aminal/main.go:56       Creating terminal...
1.5434061356787918e+09  fatal   aminal/main.go:64       Render error: Failed to create window: Failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
main.main
        /go/src/github.com/liamg/aminal/main.go:64
runtime.main
        /usr/local/go/src/runtime/proc.go:201`

On Fedora 29, xorg+radeon. Is something wrong with my system?

Thank you.

**Comment by iNode** [comment] 2018-11-28 12:06
I have similar/same issue on ubuntu 18.04, xorg+radeon.

**Comment by mathisen99** [comment] 2018-11-28 20:52
have same issue on arch.

 mathisen@tempy  ~  aminal
1.5434379450502367e+09	info	aminal/main.go:28	Allocating pty...
1.5434379450523984e+09	info	aminal/main.go:56	Creating terminal...
1.5434379450936131e+09	fatal	aminal/main.go:64	Render error: Failed to create window: Failed to create window: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig
main.main
	/tmp/yaourt-tmp-mathisen/aur-aminal-git/src/go/src/github.com/liamg/aminal/main.go:64
runtime.main
	/usr/lib/go/src/runtime/proc.go:201

**Comment by liamg** [comment] 2018-11-29 08:56
I think this may be fixed in #91 - please can you try again on master?

**Comment by liamg** [comment] 2018-11-29 09:32
Aha, and that should be fixed in #92 - does it run now?

**Comment by mathisen99** [comment] 2018-11-29 09:35
that was fast 👍 
Yes everything works now thanks!

**Comment by liamg** [comment] 2018-11-29 09:35
Awesome, thanks for your help 👍

**Comment by ktsaou** [comment] 2018-11-29 10:18
It still does not work on arch linux:

```sh
$ aminal
1.5434866332294683e+09	info	aminal/main.go:28	Allocating pty...
1.5434866332313108e+09	info	aminal/main.go:56	Creating terminal...
1.5434866332930453e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.6: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.543486633299622e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.5: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333055189e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.4: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333096368e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.3: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333136814e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.2: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333185716e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.1: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333232958e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.0: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333273106e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v3.3: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333312593e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v3.2: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
1.5434866333312926e+09	fatal	aminal/main.go:64	Render error: Failed to create window: failed to create window, please update your graphics drivers and try again
main.main
	/tmp/pamac-build/aminal-git/src/go/src/github.com/liamg/aminal/main.go:64
runtime.main
	/usr/lib/go/src/runtime/proc.go:201
```

**Comment by ktsaou** [comment] 2018-11-29 12:12
here it is:

```sh
$ sudo lspci -vnn | grep VGA -A 12
lspci: Unable to load libkmod resources: error -12
00:02.0 VGA compatible controller [0300]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [8086:0412] (rev 06) (prog-if 00 [VGA controller])
	Subsystem: Gigabyte Technology Co., Ltd Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics Controller [1458:d000]
	Flags: bus master, fast devsel, latency 0, IRQ 11
	Memory at f7400000 (64-bit, non-prefetchable) [size=4M]
	Memory at d0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [disabled] [size=64]
	Capabilities: [90] MSI: Enable- Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features

00:03.0 Audio device [0403]: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller [8086:0c0c] (rev 06)
	Subsystem: Intel Corporation Xeon E3-1200 v3/4th Gen Core Processor HD Audio Controller [8086:2010]
	Flags: bus master, fast devsel, latency 0, IRQ 16
--
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GP106 [GeForce GTX 1060 3GB] [10de:1c02] (rev a1) (prog-if 00 [VGA controller])
	Subsystem: ASUSTeK Computer Inc. GP106 [GeForce GTX 1060 3GB] [1043:85ed]
	Flags: bus master, fast devsel, latency 0, IRQ 31
	Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Legacy Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [250] Latency Tolerance Reporting
```

**Comment by mathisen99** [comment] 2018-11-29 12:37
you have the nvidia packet installed ?
did try also with a machine with nvidia card.

![](https://i.imgur.com/gRd6Hwk.png)

**Comment by ktsaou** [comment] 2018-11-29 12:39
hm... yes, everything is installed. This gpu is used for my desktop.
Is there a special opengl package needed?

**Comment by Evlos** [comment] 2018-11-30 06:50
> It still does not work on arch linux:
> 
> ```shell
> $ aminal
> 1.5434866332294683e+09	info	aminal/main.go:28	Allocating pty...
> 1.5434866332313108e+09	info	aminal/main.go:56	Creating terminal...
> 1.5434866332930453e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.6: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.543486633299622e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.5: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333055189e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.4: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333096368e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.3: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333136814e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.2: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333185716e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.1: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333232958e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v4.0: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333273106e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v3.3: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333312593e+09	warn	gui/gui.go:354	Failed to create window: Failed to create window using OpenGL v3.2: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation).. Will attempt older version...
> 1.5434866333312926e+09	fatal	aminal/main.go:64	Render error: Failed to create window: failed to create window, please update your graphics drivers and try again
> main.main
> 	/tmp/pamac-build/aminal-git/src/go/src/github.com/liamg/aminal/main.go:64
> runtime.main
> 	/usr/lib/go/src/runtime/proc.go:201
> ```

Same here.

It works fine for a while, but after I opened more than 6 windows, this error occurs.

```
λ aminal                                                           (a) 14:11:21
1.5435605608218439e+09	info	aminal/main.go:28	Allocating pty...
1.5435605608231902e+09	info	aminal/main.go:56	Creating terminal...
1.5435605608862162e+09	fatal	aminal/main.go:64	Render error: Failed to create window: Failed to create window: VersionUnavailable: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
main.main
	/home/evlos/go/src/github.com/liamg/aminal/main.go:64
runtime.main
	/usr/lib/go/src/runtime/proc.go:201
```

**Comment by Evlos** [comment] 2018-11-30 06:52
```
lspci: Unable to load libkmod resources: error -12
01:00.0 VGA compatible controller [0300]: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] [10de:1380] (rev a2) (prog-if 00 [VGA controller])
	Subsystem: NVIDIA Corporation GM107 [GeForce GTX 750 Ti] [10de:105f]
	Flags: bus master, fast devsel, latency 0, IRQ 133
	Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	Memory at f0000000 (64-bit, prefetchable) [size=32M]
	I/O ports at e000 [size=128]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [60] Power Management version 3
	Capabilities: [68] MSI: Enable+ Count=1/1 Maskable- 64bit+
	Capabilities: [78] Express Legacy Endpoint, MSI 00
	Capabilities: [100] Virtual Channel
	Capabilities: [250] Latency Tolerance Reporting
```

OS: Manjaro 18.0.0 Illyria
Kernel: x86_64 Linux 4.18.17-1-MANJARO

**Comment by ktsaou** [comment] 2018-11-30 09:03
> OS: Manjaro 18.0.0 Illyria
> Kernel: x86_64 Linux 4.18.17-1-MANJARO

Yes, it is arch based.

**Comment by liamg** [comment] 2018-12-05 12:58
Hmm, I'm stuck on this one, It might be worth raising this at the [glfw](https://github.com/go-gl/glfw) repo. I think the error is because it can't find any version of OpenGL that is usable by your graphics drivers, though I'm not sure why in your case.

**Comment by jcmartins** [comment] 2019-01-04 16:14
Package: aminal
Status: install ok installed
Maintainer: Liam Galvin
Architecture: amd64
Version: 0.7.13
Description: A Modern Terminal Emulator
Description-md5: 210d220a98a32ecfb980a8c22557dd4f

> aminal
1.5466180393044593e+09	info	aminal/main.go:28	Allocating pty...
1.5466180393277087e+09	info	aminal/main.go:56	Creating terminal...
1.546618039640688e+09	warn	gui/gui.go:394	Failed to create window: Failed to create window using OpenGL v4.6: VersionUnavailable: GLX: Failed to create context: GLXBadFBConfig.. Will attempt older version...
1.5466180396890326e+09	info	gui/gui.go:444	OpenGL version 4.5 (Core Profile) Mesa 18.2.2
**1.5466181582973995e+09	error	gui/gui.go:169	Read from pty failed: read /dev/ptmx: input/output error**
github.com/liamg/aminal/gui.(*GUI).Render.func3
	/go/src/github.com/liamg/aminal/gui/gui.go:169

 **cat /etc/lsb-release** 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Ubuntu 18.10"

**sudo lspci -vnn | grep VGA -A 12**
00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Dell HD Graphics 5500 [1028:062e]
	Flags: bus master, fast devsel, latency 0, IRQ 49
	Memory at f6000000 (64-bit, non-prefetchable) [size=16M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at f000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915

**Comment by liamg** [comment] 2019-01-27 14:16
I'm going to close this as I believe the issue is upstream.

**Closed by liamg** 2019-01-27 14:16 UTC
Labels: bug, waiting-for-info
